<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price Filter slider</name>
   <tag></tag>
   <elementGuidId>8df63418-903b-485b-adbf-f0dd61f1423e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mdc-slider__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='range']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=slider</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1d2bfe9-8c11-4898-b0f2-2ceccfe0fbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>765be099-0bb7-4b24-852c-d23969b032a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-slider__input</value>
      <webElementGuid>ee3158dc-734f-4d83-a79f-1060d2e50c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuetext</name>
      <type>Main</type>
      <value>4k</value>
      <webElementGuid>3d5df6d0-82cd-45dc-8729-c7506f96345e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1e2e37e6-6335-4a71-87a1-a3dbc8604f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>111</value>
      <webElementGuid>d37515c2-2dfa-4755-92ac-51d1422b1451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>8264</value>
      <webElementGuid>bdcc0b6d-b3a5-466b-9a8f-969106cffeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;container&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row no-gutters pt-3 ng-star-inserted&quot;]/div[@class=&quot;col-md-3 col-sm-12&quot;]/div[@class=&quot;filter-container&quot;]/app-price-filter[1]/mat-card[@class=&quot;mat-mdc-card mdc-card my-4 ng-star-inserted&quot;]/mat-card-content[@class=&quot;mat-mdc-card-content&quot;]/mat-slider[@class=&quot;mat-mdc-slider mdc-slider m-0 mat-primary mdc-slider--discrete mat-mdc-slider-with-animation&quot;]/input[@class=&quot;mdc-slider__input&quot;]</value>
      <webElementGuid>2b1fd0f2-f72c-4cd3-bcca-6d3537e2db4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='range']</value>
      <webElementGuid>4e417808-ac41-45ff-891e-ff59a32eb0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-slider/input</value>
      <webElementGuid>fa98dce1-fe48-4e5c-8ef5-c8f468144fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range']</value>
      <webElementGuid>45aeeec7-1847-4425-baed-ab78012f025e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
